name: Java Maven Build

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute Composite Action
        uses: ./.github/actions/java-build
        with:
          java-version: "17"